apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-mongodb-atlas-cluster
  title: Create MongoDB Atlas Cluster
  description: Provisions a new MongoDB Atlas Cluster on GCP using Terraform. Includes Project, Cluster (M10+), and basic security.
  tags:
    - mongodb
    - database
    - terraform
    - gcp
spec:
  owner: user:guest
  type: infrastructure

  # Input parameters for the user
  parameters:
    - title: Cluster Configuration
      required:
        - name
        - owner
        - region
        - size
        - gcp_project_id
      properties:
        name:
          title: Cluster Name
          type: string
          description: Unique name for the cluster
          ui:autofocus: true
          pattern: '^[a-z0-9-]+$'
        gcp_project_id:
          title: GCP Project ID
          type: string
          description: The GCP Project ID where resources will be deployed
        owner:
          title: Owner
          type: string
          description: Team or individual owning this resource
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
              - User
        region:
          title: GCP Region
          type: string
          description: The Google Cloud region to deploy into.
          enum:
            - EUROPE_NORTH_1
            - EUROPE_WEST_1
            - US_CENTRAL_1
          default: EUROPE_NORTH_1
        size:
          title: Cluster Tier
          type: string
          description: The instance size of the cluster.
          enum:
            - M10
            - M30
            - M50
          default: M10

  # Steps to execute
  steps:
    - id: fetch-base
      name: Fetch Terraform Skeleton
      action: fetch:template
      input:
        url: ./mongodb-atlas-template
        values:
          name: ${{ parameters.name }}
          region: ${{ parameters.region }}
          size: ${{ parameters.size }}
          owner: ${{ parameters.owner }}

    # Optional: Add a step to register the component in the catalog
    # - id: register
    #   name: Register Component
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
    #     catalogInfoPath: '/catalog-info.yaml'

    - id: publish
      name: Publish Terraform PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=piemar&repo=svenska-spel-demo-infra
        branchName: create-atlas-${{ parameters.name }}
        title: "Create Atlas Cluster: ${{ parameters.name }}"
        description: |
          Provisions a new MongoDB Atlas Cluster via Backstage.
          
          **Details:**
          - **Name:** ${{ parameters.name }}
          - **Region:** ${{ parameters.region }}
          - **Size:** ${{ parameters.size }}
          - **Owner:** ${{ parameters.owner }}
          
          This PR was automatically generated by the Backstage Scaffolder.
        targetPath: 'projects/${{ parameters.name }}'

  # Outputs to display to the user
  output:
    links:
      - title: Pull Request
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
